### PR TITLE
Using ARM64/AArch64 runners to run workflow

### PR DESCRIPTION
**Pull request by locnnil**

### CODE REVIEW

**Comment by locnnil** [comment]
## Note:

As the workflow file changed, the tests marked as required, including:
- build-and-test-amd64 (Expected: Waiting for status to be reported)
- build-arm64 (arm64) (Expected: Waiting for status to be reported)

These tests will never run, as [the new workflow](https://github.com/canonical/matter-pi-gpio-commander/actions/runs/8459343450/workflow) for build and test already incorporates both of them.

**Comment by farshidtz** [comment]
Removed the required checks.

**Review by farshidtz — APPROVED** [review]
Looks good. Thanks.

This PR supersedes #51

**Comment by farshidtz** [comment]
@locnnil I had overlooked this which changes the entire workflow to use the arm runner.
The goal was to run only the tests on paid arm runners, based on #51, because running them on QEMU wasn't feasible. This work in #51 was blocked because of libgpio incompatibility with the arm runner which was resolved by upgrading libgpio to v2 in #56.

**Comment by locnnil** [comment]
@farshidtz Okay, I'm going to open a [ new PR](https://github.com/canonical/matter-pi-gpio-commander/pull/66) to change this to run only the tests on the arm runner.

**Pull request merged**
